// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4c0Fng6e_0eYj-fsTARN32LXbq5XrAL8',
    appId: '1:631393157394:web:2ba5b8b300fa6c3a5b33cb',
    messagingSenderId: '631393157394',
    projectId: 'flawlessyou',
    authDomain: 'flawlessyou.firebaseapp.com',
    storageBucket: 'flawlessyou.firebasestorage.app',
    measurementId: 'G-8PDB3KEJ3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ct7b-OUtN_jDKGtWOzml2JqgIQCbevY',
    appId: '1:631393157394:android:e0bbe1496e95e33d5b33cb',
    messagingSenderId: '631393157394',
    projectId: 'flawlessyou',
    storageBucket: 'flawlessyou.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVKm9-JkHieBFzRfurq5MumrSLlDVrv0s',
    appId: '1:631393157394:ios:d2884b63f3246be65b33cb',
    messagingSenderId: '631393157394',
    projectId: 'flawlessyou',
    storageBucket: 'flawlessyou.firebasestorage.app',
    iosClientId: '631393157394-q7026jl38fkbheo0nrgrdst0q2054qss.apps.googleusercontent.com',
    iosBundleId: 'com.example.youtubeMessengerApp',
  );

}